import { test, expect, type Page } from '@playwright/test';
import { baselineSnapshot, crisisSnapshot, nodes, outcomes, responseSnapshots } from '../src/data';
import { getView, initialState, reducer } from '../src/simulation';

const visibleAmbientPins = (page: Page) => page.locator('.ambient-avatar-pin').evaluateAll(els => els
  .filter(el => Number((el as HTMLElement).style.opacity) > 0.05)
  .map(el => el.getAttribute('data-node')));

test('all timelines restore the same population, sentiment and snapshot time', () => {
  expect(nodes).toHaveLength(229);
  expect(new Set(nodes.map(n => n.id)).size).toBe(229);
  expect(new Set(nodes.map(n => n.z)).size).toBeGreaterThan(200);
  let s = reducer(initialState, { type: 'identity', index: 1 });
  s = reducer(s, { type: 'enter' });
  expect(s.step).toBe('society');
  expect(getView(s).history).toHaveLength(0);
  expect(reducer(s, { type: 'rumour' }).step).toBe('society');
  s = reducer(s, { type: 'tick', dt: 11.57 });
  expect(getView(s).history).toHaveLength(2);
  const before = s;
  s = reducer(s, { type: 'rumour' });
  expect(getView(s).history).toHaveLength(0);
  const firstMoment = reducer(s, { type: 'tick', dt: 3.6 });
  expect(getView(firstMoment).active).toBeUndefined();
  expect(getView(firstMoment).history).toHaveLength(1);
  const rewind = reducer(s, { type: 'back' });
  expect(rewind.elapsed).toBe(before.elapsed);
  expect(getView(rewind).to).toEqual(baselineSnapshot);
  s = reducer(s, { type: 'tick', dt: 15.23 });
  const rumour = s;
  const rumourHistory = getView(rumour).history;
  expect(rumourHistory).toHaveLength(4);
  expect(getView(s).to).toEqual(crisisSnapshot);
  expect(getView(s).progress).toBe(1);
  s = reducer(s, { type: 'respond' });
  expect(getView(s).history).toEqual(rumourHistory);
  expect(getView(s).activity).toEqual(getView(rumour).activity);
  for (const o of outcomes) {
    expect(getView(s).to).toEqual(crisisSnapshot);
    expect(s.elapsed).toBe(rumour.elapsed);
    expect(getView(s).activity).toEqual(getView(rumour).activity);
    expect(getView(s).history).toEqual(rumourHistory);
    s = reducer(s, { type: 'strategy', strategy: o.id });
    expect(s.running).toBe(true);
    s = reducer(s, { type: 'tick', dt: 14.5 });
    expect(s.step).toBe('outcome');
    expect(getView(s).history).toHaveLength(8);
    expect(getView(s).history.slice(0, 4)).toEqual(rumourHistory);
    expect(getView(s).history[4].text).toBe(o.response);
    expect(getView(s).metrics).toEqual(o.metrics);
    expect(getView(s).to).toEqual(responseSnapshots[o.id]);
    expect(Math.round(responseSnapshots[o.id].filter(x => x === 1).length / 229 * 100)).toBe(o.metrics.supportive);
    expect(Math.round(responseSnapshots[o.id].filter(x => x === -1).length / 229 * 100)).toBe(o.metrics.hostile);
    s = reducer(s, { type: 'back' });
    expect(s.step).toBe('response');
    expect(s.running).toBe(false);
    expect(getView(s).history).toEqual(rumourHistory);
  }
  expect(s.history).toHaveLength(4);
  s = reducer(s, { type: 'back' });
  expect(s.elapsed).toBe(rumour.elapsed);
  expect(getView(s).to).toEqual(crisisSnapshot);
  expect(reducer(s, { type: 'restart' })).toEqual(initialState);
});

test('desktop: genesis, mutations, all four response journeys and comparison', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', e => errors.push(e.message));
  await page.goto('/');
  await expect(page.getByRole('heading', { name: /You’re famous now.*Can you survive.*a rumour/ })).toBeVisible();
  await expect(page.locator('.graph')).toHaveAttribute('data-renderer', 'webgl');
  await expect(page.locator('.graph')).toHaveCSS('opacity', '1');
  await page.getByRole('button', { name: /Breakout actor/ }).focus();
  await expect(page.getByRole('img', { name: 'You as the breakout actor' })).toBeVisible();
  await page.screenshot({ path: 'test-results/identity-desktop.png' });
  await page.getByRole('button', { name: /Breakout actor/ }).click();
  await expect(page.getByRole('heading', { name: 'Good press travels.' })).toBeVisible();
  await expect(page.locator('.event-history')).toContainText('One to watch.');
  await expect(page.locator('.highlight-avatar-pin')).toHaveAttribute('data-node', '0');
  await expect(page.locator('.highlight-avatar-pin .logo-wire')).toBeVisible();
  await expect(page.locator('.highlight-avatar-pin')).toHaveCSS('opacity', '1');
  await expect(page.locator('.graph')).toHaveAttribute('data-motion', 'highlight');
  const firstPins = await visibleAmbientPins(page);
  expect(firstPins.length).toBeGreaterThan(3);
  expect(firstPins).not.toContain('0');
  await page.screenshot({ path: 'test-results/society-highlight.png' });
  await expect(page.getByRole('button', { name: 'Introduce a rumour' })).toBeEnabled();
  await expect(page.locator('.highlight-avatar-pin')).toHaveCount(0);
  await expect(page.locator('.graph')).toHaveAttribute('data-motion', 'ambient');
  const laterPins = await visibleAmbientPins(page);
  expect(laterPins.length).toBeGreaterThan(3);
  expect(laterPins).not.toEqual(firstPins);
  await page.screenshot({ path: 'test-results/society-desktop.png' });
  await page.getByRole('button', { name: 'Introduce a rumour' }).click();
  await expect(page.locator('.event-history')).toContainText('Someone on set needs to talk.');
  await expect(page.locator('.highlight-avatar-pin')).toHaveAttribute('data-node', '2');
  await expect(page.locator('.highlight-avatar-pin .logo-hours')).toBeVisible();
  await expect(page.locator('.event-history')).toContainText('stormed off set. Not a great look');
  await expect(page.locator('.event-history')).toContainText('CHAOS ON SET');
  await expect(page.locator('.history-event')).toHaveCount(3);
  // Reading the source should keep its position as later moments arrive.
  await page.locator('.history-scroll').evaluate(el => { el.scrollTop = 0; el.dispatchEvent(new Event('scroll')); });
  await expect(page.locator('.event-history')).toContainText('Impossible to work with.');
  await expect(page.locator('.history-scroll')).toHaveJSProperty('scrollTop', 0);
  await expect(page.getByRole('button', { name: 'New moment below' })).toBeVisible();
  await page.getByRole('button', { name: 'New moment below' }).click();
  await page.screenshot({ path: 'test-results/rumour-mutation.png' });
  await expect(page.locator('.event-history')).toContainText('Impossible to work with.');
  await expect(page.getByRole('button', { name: 'Choose a response' })).toBeEnabled();
  await expect(page.locator('.history-event')).toHaveCount(4);
  await page.screenshot({ path: 'test-results/rumour-history-desktop.png' });
  await expect(page.locator('.sentiment-key')).toContainText('31% supportive');
  await page.getByRole('button', { name: 'Before the rumour' }).click();
  await expect(page.locator('.sentiment-key')).toContainText('72% supportive');
  await expect(page.getByRole('button', { name: 'Introduce a rumour' })).toBeEnabled();
  await page.getByRole('button', { name: 'Introduce a rumour' }).click();
  await page.getByRole('button', { name: 'Choose a response' }).click();
  await expect(page.locator('.history-event')).toHaveCount(4);
  await expect(page.locator('.event-history')).toContainText('Someone on set needs to talk.');
  await page.screenshot({ path: 'test-results/response-choices.png' });
  for (const o of outcomes) {
    await expect(page.locator('.sentiment-key')).toContainText('31% supportive');
    await page.getByRole('button', { name: new RegExp(o.title.replace('+', '\\+')) }).click();
    await expect(page.locator('.highlight-avatar-pin')).toHaveAttribute('data-node', '-1');
    await expect(page.locator('.highlight-avatar-pin .portrait-0')).toBeVisible();
    await expect(page.locator('.event-history')).toContainText(o.reactions[0]);
    await expect(page.locator('.event-history')).toContainText(o.reactions[1]);
    await expect(page.locator('.event-history')).toContainText(o.reactions[2]);
    await expect(page.locator('.experience')).toHaveAttribute('data-step', 'outcome');
    await expect(page.getByRole('heading', { name: o.insight })).toBeVisible();
    await expect(page.getByRole('complementary', { name: 'Response outcome' })).toContainText(`${o.metrics.belief}%`);
    await expect(page.getByRole('complementary', { name: 'Public sentiment' })).toHaveCount(0);
    await page.getByText('Response analysis').click();
    await expect(page.locator('.statement-quote')).toBeVisible();
    await page.getByText('Response analysis').click();
    await page.screenshot({ path: `test-results/outcome-${o.id}.png` });
    await page.getByRole('button', { name: 'Try another response' }).click();
    await expect(page.locator('.history-event')).toHaveCount(4);
    await expect(page.locator('.experience')).toHaveAttribute('data-step', 'response');
  }
  await expect(page.getByText('TRIED', { exact: true })).toHaveCount(4);
  await page.getByRole('button', { name: /No response/ }).click();
  await expect(page.locator('.experience')).toHaveAttribute('data-step', 'outcome');
  await expect(page.locator('.comparison tbody tr')).toHaveCount(4);
  await page.getByRole('button', { name: 'Start over' }).click();
  await expect(page.locator('.experience')).toHaveAttribute('data-step', 'identity');
  expect(errors).toEqual([]);
});

test('mobile and reduced motion preserve the story and accessible controls', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.emulateMedia({ reducedMotion: 'reduce' });
  await page.goto('/');
  await expect(page.getByRole('button', { name: 'Motion reduced' })).toHaveAttribute('aria-pressed', 'true');
  await page.screenshot({ path: 'test-results/identity-mobile.png', fullPage: true });
  await page.getByRole('button', { name: /Pop star/ }).click();
  await expect(page.getByRole('img', { name: 'You as the pop star' })).toBeVisible();
  await expect(page.locator('.history-event')).toHaveCount(1);
  await page.getByRole('button', { name: 'Pause simulation' }).click();
  await expect(page.locator('.history-status')).toHaveText('Paused');
  await expect(page.locator('.highlight-avatar-pin')).toHaveAttribute('data-node', '0');
  await expect(page.locator('.highlight-avatar-pin')).toHaveCSS('opacity', '1');
  await expect(page.locator('.highlight-avatar-pin .logo-wire')).toBeInViewport();
  await expect(page.locator('.graph')).toHaveAttribute('data-motion', 'reduced');
  const pausedPins = await visibleAmbientPins(page);
  expect(pausedPins.length).toBeGreaterThan(0);
  expect(pausedPins.length).toBeLessThanOrEqual(7);
  await page.screenshot({ path: 'test-results/pins-mobile-paused.png', fullPage: true });
  const record = await page.locator('.history-list').innerText();
  await page.waitForTimeout(4200);
  await expect(page.locator('.highlight-avatar-pin')).toHaveCSS('opacity', '1');
  expect(await visibleAmbientPins(page)).toEqual(pausedPins);
  await expect(page.locator('.history-list')).toHaveText(record, { useInnerText: true });
  await page.getByRole('button', { name: 'Resume simulation' }).click();
  await page.getByRole('button', { name: 'Introduce a rumour' }).click();
  await page.getByRole('button', { name: 'Choose a response' }).click();
  await expect(page.locator('.history-event')).toHaveCount(4);
  await page.locator('.history-scroll').evaluate(el => { el.scrollTop = 0; });
  await page.locator('.history-event').first().scrollIntoViewIfNeeded();
  await expect(page.locator('.history-event').first()).toBeInViewport();
  await page.screenshot({ path: 'test-results/choices-mobile.png', fullPage: true });
  await page.getByRole('button', { name: /Apologise/ }).click();
  await expect(page.locator('.experience')).toHaveAttribute('data-step', 'outcome');
  await page.screenshot({ path: 'test-results/outcome-mobile.png', fullPage: true });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.getByRole('button', { name: 'Try another response' }).click();
  await expect(page.locator('.sentiment-key')).toContainText('31% supportive');
  await page.getByRole('button', { name: 'Back to the rumour' }).click();
  await page.getByRole('button', { name: 'Before the rumour' }).click();
  await page.getByRole('button', { name: 'Change identity' }).click();
  await page.getByRole('button', { name: /Veteran actor/ }).click();
  await expect(page.getByRole('img', { name: 'You as the veteran actor' })).toBeVisible();
});

test('narrow mobile keeps the hero clear and response choices reachable', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 740 });
  await page.emulateMedia({ reducedMotion: 'reduce' });
  await page.goto('/');
  const copy = await page.locator('.intro-copy').boundingBox();
  const graph = await page.locator('.graph').boundingBox();
  expect(copy!.y + copy!.height).toBeLessThan(graph!.y);
  await page.screenshot({ path: 'test-results/narrow-identity.png', fullPage: true });
  await page.getByRole('button', { name: /Veteran actor/ }).click();
  await page.getByRole('button', { name: 'Introduce a rumour' }).click();
  await page.getByRole('button', { name: 'Choose a response' }).click();
  const network = await page.locator('.graph').boundingBox();
  const controls = await page.locator('.response-choices').boundingBox();
  expect(network!.y + network!.height).toBeLessThan(controls!.y);
  await page.screenshot({ path: 'test-results/narrow-choices.png', fullPage: true });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.getByRole('button', { name: /Short denial/ }).click();
  await expect(page.locator('.experience')).toHaveAttribute('data-running', 'true');
});

test('a browser without WebGL retains the canvas story and keyboard selection', async ({ page }) => {
  await page.addInitScript(() => {
    const original = HTMLCanvasElement.prototype.getContext;
    HTMLCanvasElement.prototype.getContext = function (type, ...args) {
      if (type === 'webgl' || type === 'webgl2' || type === 'experimental-webgl') return null;
      return original.call(this, type, ...args);
    } as typeof original;
  });
  await page.goto('/');
  await expect(page.locator('.graph')).toHaveAttribute('data-renderer', 'canvas-fallback');
  await page.getByRole('button', { name: /Veteran actor/ }).focus();
  await page.keyboard.press('Enter');
  await expect(page.locator('.experience')).toHaveAttribute('data-step', 'society');
  await expect(page.locator('.event-history')).toContainText('veteran actor');
  await expect(page.locator('.highlight-avatar-pin')).toHaveAttribute('data-node', '0');
  await expect(page.locator('.highlight-avatar-pin .logo-wire')).toBeInViewport();
});
